server:
  port: 8001
spring:
  application:
    name: USER-HYSTRIX-PROVIDER
  profiles:
    active: dev
---
server:
  port: 8002
spring:
  application:
    name: USER-HYSTRIX-PROVIDER
  profiles: test
---
server:
  port: 8003
spring:
  application:
    name: USER-HYSTRIX-PROVIDER
  profiles: hh

