server:
  port: 8001
spring:
  application:
    name: USER-HYSTRIX-PROVIDER
  profiles:
    active: dev
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
---
server:
  port: 8002
spring:
  application:
    name: USER-HYSTRIX-PROVIDER
  profiles: test
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
---
server:
  port: 8003
spring:
  application:
    name: USER-HYSTRIX-PROVIDER
  profiles: hh
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
